version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Packaging LF1-index-photos..."
      - cd backend/LF1-index-photos
      - zip -r ../../LF1.zip .
      - cd ../..

      - echo "Packaging LF2-search-photos..."
      - cd backend/LF2-search-photos
      - zip -r ../../LF2.zip .
      - cd ../..

artifacts:
  files:
    - LF1.zip
    - LF2.zip
