version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Zipping LF1-index-photos..."
      - cd backend/LF1-index-photos
      - zip -r ../../LF1.zip .
      - cd ../..

      - echo "Zipping LF2-search-photos..."
      - cd backend/LF2-search-photos
      - zip -r ../../LF2.zip .
      - cd ../..

      - echo "=== DIRECTORY TREE ==="
      - pwd
      - ls -R .

artifacts:
  files:
    - LF1.zip
  name: BuildArtifactLF1
  discard-paths: yes
  
  secondary-artifacts:
  LF2Artifact:
    files:
      - LF2.zip
    name: BuildArtifactLF2
    discard-paths: yes
