version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Building LF2-search-photos..."
      - zip -r search.zip .

artifacts:
  files:
    - search.zip
